server:
  port: 9378
  servlet:
    context-path: /es

overun:
  elasticsearch:
    hostlist: 39.105.122.65:9200 #多个结点中间用逗号分隔
  course:
    index: xc_course
    type: doc
    source_field: id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_time,start_time,end_time
